### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by jack9502** [sambow23/Dell-XPS-13-7390-macOS#1]
Thank you for your EFI.After installing the MAC OS,basic functions can be used,but,I found a problem，intel power gadget core max frequency is always keep 3.9GHz,only when the battery power is less than 20%, it will drop to about 2.5GHz,core REQ frequency is always above 4GHz-4.5GHz,cpu is very hot,How to solve this problem？look forward to your help，thank you very much!

dell xps13 7390 
bios:1.9.0
CFG LOCK:UNLOCK
10710U 16GB DDR3 WD SN750 SSD 1T, Intel AX200 Realtek ALC299
MAC OS:BIG SUR 11.6

**Comment by sambow23** [comment]
Make sure there is nothing sipping CPU Usage in the background, power management should be working fine for you since you have the same CPU as me

**Comment by sambow23** [comment]
Yeah I've been having the same issue as well, though mine sits around 2W on idle. I haven't found what causes it exactly but you can potentially work around it by undervolting the CPU to get most of that battery left, I get around 5-6 hours with moderate usage now. Check the Battery section in my readme for the exact instructions.
