### ISSUE TITLE
After using new EFI Expertimental tryin sleep over 4 hours, show error message on wake from sleep.

### ISSUE THREAD

**Issue by irfanhutomo2** [sambow23/Dell-XPS-13-7390-macOS#10]
im using lastest EFI Monterey Experimental, and trying sleep for first time over 4hours of sleep, and wake up showing error popup "shutdown..." , and then tryin clean NVRAM and the message still there.
![WhatsApp Image 2022-02-13 at 1 47 23 AM](https://user-images.githubusercontent.com/97343498/153724251-f9af2f9b-18b8-4bca-a4b1-55988e6e6a17.jpeg)

**Comment by irfanhutomo2** [comment]
trying back to not experimental EFI directly delete and copy from latest stable EFI Monterey, error message still appear

**Comment by sambow23** [comment]
can you provide boot logs from hackintool? 
`Logs > System ` and put the output into a text file and upload here.
Also do you have any specific BIOS options that are changed? If its untouched other than CFG Lock it's fine

**Comment by irfanhutomo2** [comment]
i dont make any change just download the lastest and copy to EFI.

thanks for you'r support mate!!, i appreciate it
[logs.txt](https://github.com/sambow23/Dell-XPS-13-7390-macOS/files/8054648/logs.txt)

**Comment by irfanhutomo2** [comment]
first one it's from boot, this is from the system
[system logs.txt](https://github.com/sambow23/Dell-XPS-13-7390-macOS/files/8054652/system.logs.txt)

**Comment by irfanhutomo2** [comment]
oh yeah latest EFI on boot picker don't show clean NVRAM

**Comment by sambow23** [comment]
You need to press the spacebar on the opencore boot menu to view other options, its hidden by default now.
I don't see anything weird in your logs, are you sure its not another issue with your internal SSD?

**Comment by irfanhutomo2** [comment]
my ssd is brand new and i clan install the monterey, i replace the pm981 with adata ADATA SX8200PNP.
maybe i must try clean install again?

**Comment by irfanhutomo2** [comment]
maybe any suggestion on bios setting?, i disable the touch screen, webcam on bios

**Comment by sambow23** [comment]
You need to make sure the SSD is formatted with 4K sectors as not doing so can cause those issues.
Also macOS is super picky with NVMe power management, especially with 3rd party drives like your ADATA one. I would recommend using a M.2 MSATA SSD instead, saves a bunch of power too.

There is no bios options to be changed other than cfg lock and overclock lock as mentioned in the readme. The touchscreen and webcam work fine so you can leave them enabled

**Comment by irfanhutomo2** [comment]
sorry what "formatted with 4K sectors" i formated my mac like this picture.
![image](https://user-images.githubusercontent.com/97343498/153749575-5a4dd571-1b6d-4e66-9d42-6ca8fa1c50c5.png)

**Comment by sambow23** [comment]
https://github.com/Chilluminati91/Huawei-Matebook-X-Pro-2020-Hackintosh/blob/master/format-nvme-4k.md
Also please use APFS.

You need both overclock and cfg lock, one allows power management, the other allows for undervolting

**Comment by irfanhutomo2** [comment]
thanks i wil tri it!!
