### ISSUE TITLE
can 1080p screen enable HiDPI ?

### ISSUE THREAD

**Issue by irfanhutomo2** [sambow23/Dell-XPS-13-7390-macOS#12]
default resolution 1080p for 13inc display is too small icon and text, can this monitor like scaling retina?

**Comment by sambow23** [comment]
You can use [BetterDummy](https://github.com/waydabber/BetterDummy) to create fake scaled resolutions and then use HiDPI on top of it

**Comment by sambow23** [comment]
Also, install [this](https://github.com/usr-sse2/RDM/releases/tag/2.5.0) version of RDM and add the resolutions as follows in the `RDM Applet > Display # > Edit`

<img width="804" alt="Screen Shot 2022-02-22 at 1 18 52 PM" src="https://user-images.githubusercontent.com/14916663/155203195-ac062319-f8e7-428c-95cc-827b13897e0e.png">

**Comment by irfanhutomo2** [comment]
thanks for tutor!!

**Comment by irfanhutomo2** [comment]
i accidentally changed the "display" instead of the "dummy" one, i only restore the config.plist, it's that okay?

**Comment by sambow23** [comment]
Should be

**Comment by irfanhutomo2** [comment]
i try using RDM but when restart and bootup it's make display glitch, i enable HiDPI, Retina on res 1600x900, it's perfect for 13" display for me. any suggestion resolution not showing glitch?

![image](https://user-images.githubusercontent.com/97343498/155478222-595c053f-b80e-40a0-bb22-7f7d5b066d71.png)
