### ISSUE TITLE
how to set voltageshift?

### ISSUE THREAD

**Issue by irfanhutomo2** [sambow23/Dell-XPS-13-7390-macOS#13]
i see voltageshift.kext in EFI/OC/Kext, but how i follow your sugesstion to set voltageshift? like `voltageshift powerlimit 10 10` and `voltageshift offset -100 -100 -100 -100 -100 -100 -100` how i set that value

**Comment by sambow23** [comment]
If not already, download [VoltageShift](https://github.com/sicreative/VoltageShift/raw/master/voltageshift_1.25.zip) and move the `voltageshift` binary to `/usr/local/bin` via the terminal: 
`sudo cp /path/to/voltageshift /usr/local/bin`

then restart the terminal and run the commands

**Comment by irfanhutomo2** [comment]
thanks i already set the first value , but second value `voltageshift offset -100 -100 -100 -100 -100 -100 -100` make my laptop glitch and then restart, any idea whats happen?

**Comment by irfanhutomo2** [comment]
i try only `voltageshift offset -100 -100` and it's work, but are only set like that help my battery life?

**Comment by sambow23** [comment]
> thanks i already set the first value , but second value `voltageshift offset -100 -100 -100 -100 -100 -100 -100` make my laptop glitch and then restart, any idea whats happen?
> 
> my xps using i5-10210U

that means your chip cant undervolt that far, its a silicon lottery after all, not every person will be able to go that high.
just go in -5mv increments until you hit something stable

**Comment by Shaquille0atmeal** [comment]
I would recommend starting at `-75mV` and if that is unstable decrease by `-5mV` like what was said in the previous comment.

**Comment by irfanhutomo2** [comment]
then i only can set CPU and GPU voltage?

**Comment by Shaquille0atmeal** [comment]
You can change all the values. That shouldn’t be an issue.

**Comment by irfanhutomo2** [comment]
oh i can try like this? 'voltageshift offset -75 -75 -75 -75 -75 -75 -75' ? and if this not work 
i up the value to 'voltageshift offset -80 -80 -80 -80 -80 -80 -80' ?

am i right?

**Comment by Shaquille0atmeal** [comment]
What you would do if -75mV were to fail would be do DECREASE instead of INCREASE, so you would do -70mV if -75mV crashes the system. But If -75mV IS STABLE, you can try bumping it up to -80mV and see if it is stable then.

**Comment by irfanhutomo2** [comment]
thankss for your guiding i try `-80mV` and stable i think for a minutes , the i can increase to `-85mV` right?

**Comment by Shaquille0atmeal** [comment]
I would recommend doing a few things on the machine first, test it for 15 or so minutes, and if it's stable then, continue to increase until you see instabilities.

**Comment by irfanhutomo2** [comment]
can i do like this? `voltageshift offset -100 -100 -85 -85 -85 -85 -85`

**Comment by Shaquille0atmeal** [comment]
If it is stable, yes.

**Comment by irfanhutomo2** [comment]
i dont know why, when i set like that i cannot restart,

i think my stable state is ` voltageshift offset -70 -70 -70 -70 -70 -70 -70`

**Comment by irfanhutomo2** [comment]
any suggestion for free apps that run script automaticly after sleep?

**Comment by sambow23** [comment]
https://github.com/sambow23/Dell-XPS-13-7390-macOS#battery
> I use [Power Manager](https://www.dssw.co.uk/powermanager/) to apply these offsets on boot and wake from sleep (these > offsets may not work for every configuration, take caution and ymmv.)

**Comment by irfanhutomo2** [comment]
thanksss
