### ISSUE TITLE
No Wi-Fi or Bluetooth Support

### ISSUE THREAD

**Issue by Qunqun64** [sambow23/Dell-XPS-13-7390-macOS#19]
Hello all,

Thank you for your work, it's amazing! I tried to use this EFI on my XPS and had no problems with CFG lock and installation - it's great! Unfortunately, I cannot get Bluetooth and WiFi support to work. Perhaps my configuration is different, but could it be enough to cause these issues? My XPS has BIOS v1.20.0 and I am running MacOS Monterey 12.6.5. Do you have any suggestions? Perhaps there is another EFI specifically for Ventura (hopefully)?

Thank you in advance for your help, and I look forward to hearing your suggestions!

**Comment by irfanhutomo2** [comment]
try this EFI for ventura https://github.com/H3C4T0M8/Hackintosh-Dell-XPS-13-7390-OpenCore

**Comment by Qunqun64** [comment]
Thank you, it's awesome!
I tried using Ventura, and it works fine, except for WiFi and Bluetooth again...
I'll send an issue directly to the repository, maybe it will be more appropriate.
Thanks again for your link, I'm surprised I didn't see it before!
If anyone has a suggestion, I'm open to hear it ;)
