### ISSUE TITLE
Help me with the CFG Lock

### ISSUE THREAD

**Issue by zakiyys** [sambow23/Dell-XPS-13-7390-macOS#2]
Can u help me with the CFG Lock? I follow the dortania guide to unlock the CFG using modGrubShell but still get the locked CFG.

**Comment by sambow23** [comment]
Try booting into the BIOS and click `Load Factory Defaults` to make sure the efivar settings take place (it does not wipe any existing bios settings)

**Comment by zakiyys** [comment]
when should i do the load factory defaults? after i change the var to 0x00 or before i change the varval?

**Comment by sambow23** [comment]
You do the factory reset after changing the var

**Comment by zakiyys** [comment]
still cant open the cfg lock :( any suggestion?

**Comment by sambow23** [comment]
You could try dumping the BIOS yourself and see if the value to change is any different
https://github.com/dreamwhite/bios-extraction-guide/tree/master/Dell

**Comment by sambow23** [comment]
It seems the method I had on the README did not work this machine. I updated it with a method that seems to work for everyone, please see if it works for you now.

**Comment by zakiyys** [comment]
solved :) Thanks!
