### ISSUE TITLE
can i update to monterey?

### ISSUE THREAD

**Issue by irfanhutomo2** [sambow23/Dell-XPS-13-7390-macOS#5]
can i update to monterey directly from software update?

**Comment by irfanhutomo2** [comment]
thank you for replying!!! okay i will wait for new EFI from you, in big sur its working 100% and i love your work, thanks man keep it up

**Comment by sambow23** [comment]
I've updated the EFI for Monterey support, you should be able to directly upgrade without any issues.
I'm also working on fixing the battery drain issues, stay tuned.

**Comment by irfanhutomo2** [comment]
Thanks!!!
