### ISSUE TITLE
USB-C to HDMI/DP using dongle cannot shown

### ISSUE THREAD

**Issue by irfanhutomo2** [sambow23/Dell-XPS-13-7390-macOS#8]
im using lastest monterey EFI

**Comment by irfanhutomo2** [comment]
sorry for bad english, when i use dongle to external display using HDMI, it's say " no signal "

**Comment by irfanhutomo2** [comment]
problem solve i change SMBIOS back to = MacBookAir9,1

**Comment by sambow23** [comment]
HDMI/DP via USB-C should now work on both EFIs
